name = "nostr-bot"
main = "src/index.js"
compatibility_date = "2024-12-01"

# WebSocket接続を有効化
[env.production]
compatibility_flags = [ "nodejs_compat" ]

[triggers]
crons = [
  "55 * * * *",  # 毎時55分に実行
]

[vars]
NOSTR_RELAYS = "wss://relay.damus.io,wss://nos.lol"

# デバッグ用の追加設定
[observability]
enabled = true